//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('chatGroups')
export class chatGroupsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  groupName: string;

  @Column('text', { nullable: true })
  groupDescription: string;

  @Column('date', { nullable: true })
  creationDate: Date;

  @Column('integer', { nullable: true })
  listOfMemberIds: number;
}
