//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="Create a chatting app where short films can be shared like the status feature in what's app" />
    <CardContent>
      It should be like what's app but with a modern dark cyber punk type feel
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
